export enum GameEvents {
    CREATE_ROOM = 'createRoom',
    CHECK_ROOM = 'checkRoom',
    JOIN_ROOM = 'joinRoom',
    LEAVE_ROOM = 'leaveRoom',
    START_GAME = 'startGame',
    STOP_GAME = 'stopGame',
    PAUSE_GAME = 'pauseGame',
    RESUME_GAME = 'resumeGame',
    CHANGE_NICKNAME = 'changeNickname',
    BECOME = 'become',
    REQUEST_TIMER = 'requestTimer',
    GET_OWNER_KEY = 'getOwnerKey',
    GET_MEMBERS = 'getMembers',
    GET_NICKNAME = 'getNickname',
    GET_ROOM_STATUS = 'getRoomStatus',
    GET_ACT_FLAG = 'getActFlag',
    GET_PLAYERS = 'getPlayers',
    GET_RESTRICTIONS_TO_START = 'getRestrictionsToStart',
    GET_TIMER = 'getTimer',
    GET_ALL_LOG_RECORDS = 'getAllLogRecords',
    GET_LOG_RECORD = 'getLogRecord'
}